name: Deploy the web app to AWS S3
description: This is a custom javascript action
inputs:
  bucket:
    description: The name of the bucket.
    required: true
  bucket-region:
    description: The region of the bucket.
    required: false
    default: "us-east-1"
  dist-folder:
    description: The folder containing the deployable files.
    required: true
outputs:
  website-url:
    description: This is the live url of the website.
runs:
  using: "node16"
  main: "main.js"
